### ISSUE TITLE
Add Required Plugin header field to Header Requirements

### ISSUE THREAD

**Issue by damiencarbery** [WordPress/Documentation-Issue-Tracker#1531] opened 2024-04-09 17:41 UTC
## Issue Description
I suggest adding the new `Required Plugins` header field to the Header Fields page. The header field was introduced in 6.5.

## URL of the Page with the Issue
https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

## Section of Page with the issue
Header Fields: https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields

## Why is this a problem?
WordPress 6.5 introduced a new header field - `Required Plugins`. And it is a very useful feature to help users.

## Suggested Fix
Add text like the following to the `Available header fields` list. This text is copied from the page mentioned in the 6.5 release notes.
https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/

**Requires Plugins**: This must contain a comma-separated list of WordPress.org-formatted slugs for its dependencies, such as my-plugin (my-plugin/my-plugin.php is not supported). It does not support commas in plugin slugs.

**Comment by flexseth** [comment] 2024-04-09 18:16
> I suggest adding the new `Required Plugins` header field to the Header Fields page.

Hey @damiencarbery - I've requested the change in the Plugins Handbook repo. The handbook is kind of in limbo right now due to some change decisions being made. If I can get to making the PR to update it, I will...

Duplicate of 
- https://github.com/WordPress/developer-plugins-handbook/issues/10

---

Labeling for DevHub and I'll keep the issue open so both can be closed out when the doc is updated.

**Comment by stevenlinx** [comment] 2024-04-19 12:43
1.)
> "I suggest adding the new `Required Plugins` header field..."

> "WordPress 6.5 introduced a new header field - `Required Plugins`. And it is..."

I think there are errors here. It should be `Requires Plugins` with a `s`

2.)
It seems @audrasjb has already updated the page. 

But @audrasjb , will you please open an Issue as well next time please? Thank you.

**Closed** 2024-04-22 15:24 UTC
Labels: developer documentation (DevHub), plugins, [Status] Done

**Comment by audrasjb** [comment] 2024-04-22 15:30
> But @audrasjb , will you please open an Issue as well next time please? Thank you.

Ok!
