### ISSUE TITLE
Page stylings issue

### ISSUE THREAD

**Issue by HILAYTRIVEDI** [WordPress/Documentation-Issue-Tracker#259] opened 2022-03-29 04:57 UTC
## Issue Description
While I visited the Administration Menus documentation page. The page styling appears to be horrible.

## URL of the Page with the Issue
https://developer.wordpress.org/themes/functionality/administration-menus/#top-level-menus

Video for the issue: https://www.awesomescreenshot.com/video/8112955?key=b19ffff3c2b86a01253cbec26483cabf

**Comment by stevenlin-x** [comment] 2022-03-29 05:11
@HILAYTRIVEDI ,

You were quick in reporting issues.

This was an accident while I was working on #255.

The styling issues were caused by the Visual Editor not properly formatting when you edit (adding <pre> unnecessarily)

It was fixed in less than 15 min.

**Comment by HILAYTRIVEDI** [comment] 2022-03-29 05:17
HI @stevenlin-x, Should I close this issue then?

**Comment by stevenlin-x** [comment] 2022-03-29 06:52
@HILAYTRIVEDI ,

Yes. I'll close it.

**Closed** 2022-03-29 06:52 UTC
