### ISSUE TITLE
Incorrect wording in Theme Developer Handbook > Theme Functions

### ISSUE THREAD

**Issue by jjjsmith** [WordPress/Documentation-Issue-Tracker#646] opened 2023-01-25 06:46 UTC
## Issue Description

There is text on the "Theme Functions" page in the Theme Developer Handbook that makes an incorrect statement about naming functions in plugins and functions.php.

## URL of the Page with the Issue

https://developer.wordpress.org/themes/basics/theme-functions/

## Section of Page with the issue

There's a red info box that says:  "If a WordPress plugin calls the same function, or filter, as you do in your functions.php, the results can be unexpected, even causing your site to be disabled."

## Why is this a problem?

That statement is incorrect.  I think it's meant to state that a plugin shouldn't have a function with the same name as a function in functions.php.

## Suggested Fix

If I'm correct, then here's my suggestion for how I would state that:

"If a function or filter in a WordPress plugin has the same name as a function in functions.php, the results can be unexpected, even causing your site to be disabled.  A good practice is for function names in a plugin to be prefixed with the plugin name, eg ‘plugin_name_do_this()’.”

**Comment by zzap** [comment] 2023-01-25 06:46
Heads up @WordPress/docs-issues-coordinators, we have a new issue open. Time to use 'em labels.

**Comment by sagargurnani99** [comment] 2023-02-15 15:02
I would like to work on this issue. Please assign it to me?

**Comment by carolinan** [comment] 2023-02-16 06:34
I don't think the theme developer handbook should include instructions for naming functions in plugins.
It may sound as if the handbook is encouraging developers to change the function name in someone else's plugin.

**Comment by sagargurnani99** [comment] 2023-02-16 11:18
@carolinan The page (link in issue description) compares a theme and a plugin for the developers to understand the difference between the two. That's why it includes the instructions for naming functions in plugins, such that, the functions don't have names in common.

So, I believe that having this piece of information makes sense. :)

**Comment by carolinan** [comment] 2023-02-17 01:35
But the statement that is mentioned in the issue is not incorrect.
Both theme and plugin developers are responsible for using prefixed function names.

**Comment by carolinan** [comment] 2023-02-22 05:44
What if we compromise, can you suggest a paragraph or two that explains that avoiding naming conflicts is the responsibility of **both** the theme developer and plugin developer?

**Comment by sagargurnani99** [comment] 2023-02-22 18:44
@carolinan What do you think about this?

> In WordPress, naming conflicts can occur when two or more functions, classes, or variables have the same name. This can cause errors or unexpected behavior in a WordPress site. It is the responsibility of both the theme developer and plugin developer to avoid naming conflicts in their respective code.
> 
> Theme developers should ensure that their functions, classes, and variables have unique names that do not conflict with those used by WordPress core or other plugins. They should also prefix their function and class names with a unique identifier, such as the theme name or abbreviation, to minimize the chances of a naming conflict.

**Comment by sagargurnani99** [comment] 2023-03-03 18:44
@carolinan Any thoughts?

**Comment by carolinan** [comment] 2023-03-17 05:31
I have added the suggested text as a replacement for the old warning. The update is published.
I will close the issue as completed, but you can still comment on it, I am unsure of if @jjjsmith has reviewed the suggested text.

Please provide your wordpress.org usernames, so that I can add you to the credits page.
https://developer.wordpress.org/themes/credits/

**Closed** 2023-03-17 05:31 UTC
Labels: developer documentation, tracking issue, themes

**Comment by sagargurnani99** [comment] 2023-03-17 09:34
Thanks @carolinan, following is my Wordpress.org username:
- @sagargurnani
