### ISSUE TITLE
[HelpHub] Site Logo 

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#193] opened 2022-03-02 19:00 UTC
## What is the new page you are requesting?

New article required for the Site Logo block

## General

- [x] make sure all screenshots are relevant for the current version (5.9)
- [x] update changelog at the end of the article

**Comment by zzap** [comment] 2022-03-07 11:11
Duplicate of #88

**Comment by femkreations** [comment] 2022-06-29 20:45
https://wordpress.org/support/article/site-logo-block/ New page created and updated for 6.0 with screenshots, content and video. @zzap

**Closed** 2022-07-19 14:31 UTC
Labels: user documentation, duplicate, 5.9, new document, block editor
