### ISSUE TITLE
Removing technical details from the selected end user docs

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#70] opened 2021-11-11 19:05 UTC
## Issue Description
Related to #30, selecting the following pages from which the technical details will be removed 

## URL of the Page with the Issue
https://wordpress.org/support/article/using-permalinks/
https://wordpress.org/support/article/login-trouble/

## Why is this a problem?

Hosting providers take care of supporting WordPress. hence these details need not be included in the end-user docs.

## Suggested Fix

Rewrite the selected end-user docs and submit them for review.

**Comment by femkreations** [comment] 2021-11-17 03:04
Using Permalinks: https://docs.google.com/document/d/12gS7fdCft62oA8_xdpXxMFOmi1prg43Za7tP_8p9EIY/edit

**Comment by femkreations** [comment] 2021-11-17 17:14
Login Trouble: https://docs.google.com/document/d/16p5e1IC_PUfADsZ3L6u1-NkM9awkM1jhI66r8f9UVh4/edit

**Comment by atachibana** [comment] 2021-12-12 15:10
@femkreations 
It's very well edited and easy to understand for all users. 😊
Thank you.

Using Permalinks:
One minor thing
"When want to share a blog post ..." should be "When you want to ..."

Login Trouble:
I believe almost all failure must be caused by password problem. How about swapping the order of paragraph Enable Cookies and Password Problems?

Also we have to remember those technical tips to solve the issue such as MySQL editing.

**Comment by femkreations** [comment] 2022-03-02 17:36
The page https://wordpress.org/support/article/login-trouble/ has been updated.

**Comment by atachibana** [comment] 2022-12-11 13:30
@femkreations 
Sorry for late responses. I confirmed your fixes and close this issue.

**Closed by atachibana** 2022-12-11 13:30 UTC
Labels: tracking issue, Content Review
