### ISSUE TITLE
[HelpHub] [6.4] Footnotes Block

### ISSUE THREAD

**Issue by femkreations** [WordPress/Documentation-Issue-Tracker#1203] opened 2023-10-18 17:53 UTC
## Updates for 6.4
- [x] Add missing placeholder instructions text. [54056](https://github.com/WordPress/gutenberg/pull/54056)
- [x] Add typography, dimensions, and border block supports. [53044](https://github.com/WordPress/gutenberg/pull/53044)
- [x] Add link, background and text color support. [52897](https://github.com/WordPress/gutenberg/pull/52897)
- [x] show in inserter and placeholder. [52445](https://github.com/WordPress/gutenberg/pull/52445)
- [x] Require confirmation before removing Footnotes. [52277](https://github.com/WordPress/gutenberg/pull/52277)

## Reference
- [ ] [Pls refer for the previous versions tasks here](https://github.com/WordPress/Documentation-Issue-Tracker/issues/942)

## General
- [ ] Make sure all screenshots are relevant to the latest version 
- [ ] Make sure videos, if any, are up to date 
- [ ] Add ALT tags for the images
- [ ] Make sure the headings are in sentence case
- [ ] Convert all reusable blocks to a ‘regular block’.
- [ ] Update the changelog at the end of the article

**Comment by zunaid321** [comment] 2023-11-04 19:54
@femkreations @abhansnuk 

Would like to work on this one. Please assign it to me.

Thank you!

**Comment by zunaid321** [comment] 2023-11-05 14:55
Add missing placeholder instructions text. https://github.com/WordPress/gutenberg/pull/54056 

We improved the user experience in the most recent update by giving placeholder instructions for scenarios where the Footnotes block is not available for custom post types. This enhancement seeks to provide users with clearer guidance by providing instructions when the Footnotes block is missing in specified instances.

![before-delete-navigation](https://user-images.githubusercontent.com/240569/264331403-149f4175-e1f7-4b13-9235-8e6eaf79d4b8.png)

**Comment by zunaid321** [comment] 2023-11-05 15:07
Add typography, dimensions, and border block supports. https://github.com/WordPress/gutenberg/pull/53044

The Footnotes block has been improved with more design flexibility in this release. The block now has settings for typography, dimensions, and border. Color support has been adjusted, with link and text now being the default, rather than background and text. These modifications attempt to give users more options for modifying the style of the Footnotes block, including more options for typography, dimensions, borders, and color choices.

![footnotes-block-support](https://user-images.githubusercontent.com/1645628/256562347-7b1eac9e-9265-4859-9a84-837db3166e8d.png)

**Comment by zunaid321** [comment] 2023-11-05 15:17
Add link, background and text color support. https://github.com/WordPress/gutenberg/pull/52897

Improved the Footnotes block in this recent release by adding support for link, background, and text color. Users may now quickly access link controls by selecting them from the Color Options menu, resulting in a uniform and user-friendly experience across different blocks.

![](https://user-images.githubusercontent.com/1645628/255638320-7be74e0e-7c6e-4d30-8206-365006104ed1.png)
![](https://user-images.githubusercontent.com/1645628/255638977-bc7f57b7-f641-44bc-9adc-ce12c346be4e.png)

**Comment by zunaid321** [comment] 2023-11-05 15:24
Show in inserter and placeholder. https://github.com/WordPress/gutenberg/pull/52445 

Since removing the footnotes block is allowed, the update aims to make re-inserting it more convenient. Additionally, the footnotes block is now displayed in the inserter for improved discoverability, even if anchors are not yet inserted into the content. This modification strеamlinеs and improvеs thе discovеrability of thе footnotеs block, consistеnt with thе goal of crеating a morе usеr-friеndly еxpеriеncе. While the current placeholder text is a starting point, future refinements may include instructions on how to insert anchors.

![](https://user-images.githubusercontent.com/150562/252359900-a26b84a6-397e-4de3-835f-189b628752f2.png)

**Comment by zunaid321** [comment] 2023-11-05 15:29
Require confirmation before removing Footnotes. https://github.com/WordPress/gutenberg/pull/52277

Now, attempting to remove a Footnotes block triggers a warning regarding the removal of the Footnotes block. This informs the user about the removal and requires their confirmation before proceeding.

![](https://user-images.githubusercontent.com/150562/250882298-f01810fe-d57d-4b0a-bdf9-656556c1d2c9.png)

**Comment by zunaid321** [comment] 2023-11-05 15:30
@femkreations @abhansnuk 

Please review the above changes. 

Thank you.

**Comment by abhansnuk** [comment] 2023-11-08 17:03
> Add missing placeholder instructions text. [WordPress/gutenberg#54056](https://github.com/WordPress/gutenberg/pull/54056)
> 
> The user experience was enhanced in the most recent update by giving placeholder instructions for scenarios where the Footnotes block is not available for custom post types. This enhancement seeks to provide users with clearer guidance by providing instructions when the Footnotes block is missing in specified instances.
> 
> ![placeholder-instructions](https://user-images.githubusercontent.com/240569/264331403-149f4175-e1f7-4b13-9235-8e6eaf79d4b8.png)

In this image @zunaid321, is there a way to get this screenshot without the toolbar blocking the text? Thanks.

**Comment by abhansnuk** [comment] 2023-11-08 17:08
> Require confirmation before removing Footnotes. [WordPress/gutenberg#52277](https://github.com/WordPress/gutenberg/pull/52277)
> 
> Now, attempting to remove a Footnotes block triggers a warning regarding the removal of the Footnotes block. This informs the user about the removal and requires their confirmation before proceeding.
> 
> ![](https://user-images.githubusercontent.com/150562/250882298-f01810fe-d57d-4b0a-bdf9-656556c1d2c9.png)

Suggest a rephrase and to emphazise that the removal of the block will not remove the footnote numbering in the the content.

Suggest a change like this: "Now, attempting to remove a Footnotes block triggers a warning regarding its removal and its impact. It advises that footnote references in the content area will continue to show if the block is removed. The user is required to confirm the deletion request before the block is deleted."

**Comment by abhansnuk** [comment] 2023-11-08 17:20
> Show in inserter and placeholder. [WordPress/gutenberg#52445](https://github.com/WordPress/gutenberg/pull/52445)
> 
> Since removing the footnotes block is allowed, the update aims to make re-inserting it more convenient. Additionally, the footnotes block is now displayed in the inserter for improved discoverability, even if anchors are not yet inserted into the content. This modification strеamlinеs and improvеs thе discovеrability of thе footnotеs block, consistеnt with thе goal of crеating a morе usеr-friеndly еxpеriеncе. While the current placeholder text is a starting point, future refinements may include instructions on how to insert anchors.
> 
> ![](https://user-images.githubusercontent.com/150562/252359900-a26b84a6-397e-4de3-835f-189b628752f2.png)

@ellatrix and @bph could you please just review this edited text for the HelpHub is still accurate. Thanks.
"From 6.4, the Footnotes block can be removed, a provision has been made to make re-insertion easier [[Can we say how please?]]. Additionally, the footnotes block is now displayed in the inserter for improved discoverability. It will show even if anchors are not yet inserted into the content. This modification strеamlinеs and improvеs thе discovеrability of thе Footnotеs block, with thе wider goal of crеating a morе usеr-friеndly еxpеriеncе. The text in the placeholder is a starting point, future refinements may include instructions on how to insert anchors."

Thanks.

**Comment by abhansnuk** [comment] 2023-11-08 17:23
https://github.com/WordPress/Documentation-Issue-Tracker/issues/1203#issuecomment-1793765745

Edit: "Improvements to the Footnotes block in the 6.4 release with support for link, background, and text color. Users may now quickly access link controls by selecting them from the Color Options menu, resulting in a uniform and user-friendly experience across different blocks."

Thanks Zunaid.

**Comment by abhansnuk** [comment] 2023-11-08 17:28
https://github.com/WordPress/Documentation-Issue-Tracker/issues/1203#issuecomment-1793763395

The final part of the sentence does not seems to duplicate the earlier sentence. "...including more options for typography, dimensions, borders, and color choices." Can we share the kind of options within these or delete this? Thanks Zunaid.

**Comment by zunaid321** [comment] 2023-11-09 19:47
> > Add missing placeholder instructions text. [WordPress/gutenberg#54056](https://github.com/WordPress/gutenberg/pull/54056)
> > The user experience was enhanced in the most recent update by giving placeholder instructions for scenarios where the Footnotes block is not available for custom post types. This enhancement seeks to provide users with clearer guidance by providing instructions when the Footnotes block is missing in specified instances.
> > ![placeholder-instructions](https://user-images.githubusercontent.com/240569/264331403-149f4175-e1f7-4b13-9235-8e6eaf79d4b8.png)
> 
> In this image @zunaid321, is there a way to get this screenshot without the toolbar blocking the text? Thanks.
> 
> Update: it does not look like it is possible. Wonder if we can do anything about the text behind it as it may confuse the user looking at the image.

Is this okay? @abhansnuk 

![](https://github.com/WordPress/Documentation-Issue-Tracker/assets/5287486/92c1e2bd-ed1e-4d50-954a-f910f11bd24e)

**Comment by zunaid321** [comment] 2023-11-09 19:52
> Now, attempting to remove a Footnotes block triggers a warning regarding its removal and its impact. It advises that footnote references in the content area will continue to show if the block is removed. The user is required to confirm the deletion request before the block is deleted.

The text you have mentioned in the reply, is okay. 

Here is the updated text:

Now, attempting to remove a Footnotes block triggers a warning regarding its removal and its impact. It advises that footnote references in the content area will continue to show if the block is removed. The user is required to confirm the deletion request before the block is deleted.

Do let me know if I need to add anything in your reply, since I think it is sufficient. @abhansnuk

**Comment by zunaid321** [comment] 2023-11-09 19:57
> [#1203 (comment)](https://github.com/WordPress/Documentation-Issue-Tracker/issues/1203#issuecomment-1793765745)
> 
> Edit: "Improvements to the Footnotes block in the 6.4 release with support for link, background, and text color. Users may now quickly access link controls by selecting them from the Color Options menu, resulting in a uniform and user-friendly experience across different blocks."
> 
> Thanks Zunaid.

Yes, the edited description seems fine. Lets go with your one!

**Comment by zunaid321** [comment] 2023-11-09 20:01
> The Footnotes block has been improved with more design flexibility in this release. The block now has settings for typography, dimensions, and border. Color support has been adjusted, with link and text now being the default, rather than background and text. These modifications attempt to give users more options for modifying the style of the Footnotes block, including more options for typography, dimensions, borders, and color choices.

Edited:

The Footnotes block has been improved with more design flexibility in this release. The block now has settings for typography, dimensions, and border control. Color support has been adjusted, with link and text now being the default, rather than background and text. These modifications attempt to give users more flexibility when it comes to modifying the Footnotes block.

Thanks for reviewing the changes! 

Would like to request for a 2nd review of this issue. @abhansnuk @femkreations

**Comment by nalininsbs** [comment] 2023-11-12 22:22
@zzap am I right that these edits would need to be made by someone with edit access to documentation CMS. If you are happy with the latest version would you like to add them to the CMS, or could Zunaid be given edit access? Thank you.
Thank you Abha for the first edit.

**Comment by abhansnuk** [comment] 2023-11-14 18:59
Thank you for the general question which was raised in today's docs triage meeting. Summary below.

Confirmed in documentation meeting November 14, 2023 that new contributors in particular are not expected to have to edit existing posts in addition to adding revisions to the relevant documentation tracking issue on GitHub. The reviewers for the issue, on completion of the discussion on the issue, can make the changes and update the issue. This can alternatively be done by someone who is designated as a reviewer role on GitHub for the documentation tracker, and they can update the issue with the action taken too.

In terms of specifics on this issue, once this particular update has been reviewed by two reviewers and is ready for updating on the site, Zunaid can be set up to do this and given some links to information to read for Editors. 😄

**Comment by nalininsbs** [comment] 2023-11-21 15:20
Raised at the docs meetings 14 and 21 November 2023. Needs technical review.

**Comment by abhansnuk** [comment] 2023-12-05 14:01
@bph thanks for looking at that [specific query](https://github.com/WordPress/Documentation-Issue-Tracker/issues/1203#issuecomment-1802330979), was that reworded paragraph still correct please?

**Comment by Leonardus-Nugraha** [comment] 2023-12-12 07:18
@abhansnuk I have reviewed and moved the updates by @zunaid321 to the article: https://wordpress.org/documentation/article/footnotes-block/ 
Some of the text are replacing the old ones and I made some edit to make sure they flow nicely

**Comment by zunaid321** [comment] 2023-12-12 08:59
Thank you so much everyone! This is the first article that got updated with my notes! 🚀 

Special thanks to @abhansnuk for guiding me!

**Closed** 2024-01-23 08:06 UTC
Labels: user documentation (HelpHub), block editor, medium priority, 6.4
