### ISSUE TITLE
Update links inside the posts-screen DOC

### ISSUE THREAD

**Issue by TukuToi** [WordPress/Documentation-Issue-Tracker#26] opened 2021-08-29 04:00 UTC
## Issue Description
In this DOC https://wordpress.org/support/article/posts-screen/, there are several links intended to be anchor links, but they lead to other (irrelevant) pages.

## URL of the Page with the Issue
https://wordpress.org/support/article/posts-screen/

## Section of Page with the issue
Example:
https://wordpress.org/support/article/posts-screen/#actions > BULK EDIT

## Why is this a problem?
There are links that are intended to link back to anchors on the same page.
Clicking those, however leads to pages like https://codex.wordpress.org/#Editing%20Individual%20Posts instead of the actual anchor.

## Suggested Fix
Go thru the DOC, check each #anchor link and make sure it points to the correct on-page anchor.
Example in BULK EDIT Section:
` selected`, `Bulk Action`, `Applied` all lead to other pages.
The correct anchors would be (probably):
https://wordpress.org/support/article/posts-screen/#selection
https://wordpress.org/support/article/posts-screen/#actions
etc

**Comment by MuhammadFaizanHaidar** [comment] 2021-09-21 15:03
@atachibana I am not able to reproduce this issue. All the anchor links are pointing to the correct on-page anchor.

![anchor](https://user-images.githubusercontent.com/44171332/134196130-4d9e8ef7-fd57-4de6-a692-32441da06661.PNG)

**Comment by MuhammadFaizanHaidar** [comment] 2021-09-21 15:13
@TukuToi yeah now that's a bug can you please update the section of page with issue? Thanks

**Comment by TukuToi** [comment] 2021-09-21 15:15
That is since the begin the proper section.
https://wordpress.org/support/article/posts-screen/#actions
It is the only link leading to that section

The Example in BULK EDIT Section has no hyperlink, but it is mentioned in my suggested fix section:
>Example in BULK EDIT Section:
>selected, Bulk Action, Applied all lead to other pages.

**Comment by MuhammadFaizanHaidar** [comment] 2021-09-21 16:09
@TukuToi I have updated anchor links and some URLs that were leading no where. Can you please counter verify. Thanks

**Comment by TukuToi** [comment] 2021-09-22 04:20
1. Inside string `so see the Bulk Edit section for details on the Bulk Editing process.` holds a link that still leads to wrong section, it says `Bulk Edit section` but leads to `#action`
In fact `Bulk Edit section` is not even a section, it has no link, so either we need to add a link to it, or remove that anchor 
2. Inside this `This dropdown allows you to select, by date, which Posts are displayed in the Table of Posts. By default, “Show all dates” is selected and all of your Posts are displayed.` it links to https://codex.wordpress.org/#Table%20of%20Posts
Same inside `This dropdown allows you to select, by Category, which Posts are displayed in the Table of Posts. By default, “Show all categories” is selected and all of your Posts are displayed.`

I believe that is it, at least, it is what I see when I click on each link in that page

**Comment by MuhammadFaizanHaidar** [comment] 2021-09-22 04:35
For part 1 : I think till we have a valid link I can remove that anchor.
For part 2  :  I have updated the anchor links.

**Comment by TukuToi** [comment] 2021-09-22 04:54
Looking good to me!

**Comment by MuhammadFaizanHaidar** [comment] 2021-09-22 04:56
Thanks I added a link to Bulk Edit sub heading making it an anchor.

**Comment by jennydupuy** [comment] 2021-09-23 22:51
Thanks for this fix but why it is not indicated in a change log.
For teams that translate the documentation and report the changes made to the original documentation, it's hard to find where the change is located.
In the French team, we use https://developerka.org/helphub-updates/ to see which posts have been updated but often we have to scan the content to find the change made. So the changelog is valuable to find the changes.

**Comment by MuhammadFaizanHaidar** [comment] 2021-09-24 02:49
> Thanks for this fix but why it is not indicated in a change log.
> For teams that translate the documentation and report the changes made to the original documentation, it's hard to find where the change is located.
> In the French team, we use https://developerka.org/helphub-updates/ to see which posts have been updated but often we have to scan the content to find the change made. So the changelog is valuable to find the changes.

Hi @jennydupuy thanks for guidance my Locale is Urdu and I can't find one in the language select. Can you please guide me further how can I add these changes to the changelog. Thanks

**Comment by zzap** [comment] 2021-09-25 15:35
> Thanks for this fix but why it is not indicated in a change log.
> For teams that translate the documentation and report the changes made to the original documentation, it's hard to find where the change is located.
> In the French team, we use https://developerka.org/helphub-updates/ to see which posts have been updated but often we have to scan the content to find the change made. So the changelog is valuable to find the changes.

@jennydupuy the change was not in content just fixing destinations of links inside the article. Link was pointing on a section in the same article. It was wrong and fixed now. These changes shouldn't effect any locale really.

**Closed by zzap** 2021-09-25 15:35 UTC
Labels: bug, user documentation, good first issue

**Comment by zzap** [comment] 2021-09-25 15:37
@MuhammadFaizanHaidar @TukuToi 

Please make pull requests with your usernames added to this document: https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/CONTRIBUTORS.md

Thank you

**Comment by jennydupuy** [comment] 2021-09-27 08:21
I agree with you @zzap, it has no impact for the locales since the link anchor will be different in each locale, but the post is mentioned as updated and the fact that there is no change log forces the locales to look for the change, thus spending time for nothing. My goal in this request is just to save time. Thanks

**Comment by TukuToi** [comment] 2021-09-27 08:28
1. There has not been any PR for this issue here AFAIK, at least, I did not create one, and I cannot see any PR linked to this Ticket neither any PR related to this ticket in the PR list
2. If we need to keep updated some sort of list or doc we _need to clarify this somewhere else than in this ticket_
3. There is no mention on this or of PR creation or of adding our usernames to any contributor files on the readme of this project, and if any of this is required, then likely it has to be mentioned on https://github.com/WordPress/Documentation-Issue-Tracker

This ticket was a report of an error, fixed (I do not know how you do this, wether by direct edit or PR or...) by @MuhammadFaizanHaidar and thus, closed and not the place to discuss workflows IMO.

No one will find the "how to" when they are new or old to the project, if we nest and hide it inside this single, on-topic _issue_ that now is resolved.

**Comment by zzap** [comment] 2021-09-27 10:54
@TukuToi 

1. End user docs (HelpHub) is edited directly in WordPress article as we don't have GitHub repository connected to it. I have reviewed changes before closing this issue as fixed. This same procedure will apply to parts of DevHub as well.
2. Agree. I'm open for suggestions but in new issue.
3. Agree. I created issue for it https://github.com/WordPress/Documentation-Issue-Tracker/issues/40

@jennydupuy as I said in No2 here, I agree. Let's discuss in new issue how we are going to handle this. What we want to avoid is having changelog longer than the content itself and above the feedback form, so maybe this is a good time to rethink what we already have for end user block editor docs (maybe even just putting changelog on second page using `<!--nextpage-->` tag).

**Comment by TukuToi** [comment] 2021-09-27 10:56
@zzap thanks - I am then more confused as before why wed need to add some username to a list when making PRs 😃 
If we do not make PRs... what is the point of adding the username to the list as mentioned here https://github.com/WordPress/Documentation-Issue-Tracker/issues/26#issuecomment-927138265?
